import Head from "next/head";

import CategoriesSection from "components/CategoriesSection";
import HeroSection from "components/HeroSection";

export default function Home() {
  return (
    <>
      <Head>
        <title>Audiophile-HomePage</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <HeroSection />
        <CategoriesSection />
      </main>
    </>
  );
}
